name = "Frenpack"
author = "Deveyus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf0f1754d52e55c1b8ede9d2e13b707408bb26909fc69a6b1304f0d9f4bd8a15"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
