name = "Frenpack"
author = "Deveyus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6aa35ab7aca977e07b4a92e7baa3cc54695caf3cf9bafee672718c3833c5c6ec"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
